### ISSUE TITLE
[Feature Request] Show PDF on lockscreen

### ISSUE THREAD

**Issue by Tibladar** [michaeltroger/greenpass-android#136]
Sometimes people want to hold the phone in their hand to better hold the PDF in front of a reader or to better type off a code. Since the smartphone remains unlocked during this process, it isn't very secure, since you are giving away access to your smartphone.

Of course, you could say that you don't let the phone out of your hand, but would it be possible (e.g. as a setting) to display the current open PDF on the lockscreen when the app is open?

The app Transportr (https://github.com/grote/Transportr) does this for the current shown bus route: https://github.com/grote/Transportr/blob/187b5e7765e0f01813f806bf3500d12175cd78cf/app/src/main/java/de/grobox/transportr/trips/detail/TripDetailActivity.java#L82

**Comment by kylosus** [comment]
This would be tremendously useful, I unfortunately have to hand over my phone unlocked quite often at passport control and similar secured booths.

**Comment by michaeltroger** [comment]
Thx for the suggestion.
I implemented a setting that allows to have access to the PDFs on the lock screen.
https://github.com/michaeltroger/greenpass-android/pull/159

I understand that locking it to a specific PDF would even be nicer, but there is no "Single PDF screen" yet and I don't have the time resources to create one now. Will keep it in mind for the future though.
Hope it is still of any use for you
