### ISSUE TITLE
[Feature request] Add support for regular barcodes

### ISSUE THREAD

**Issue by michaeltroger** [michaeltroger/greenpass-android#140]
Original issue: https://github.com/michaeltroger/greenpass-android/issues/73
requested by [AminGholizad](https://github.com/AminGholizad)

**Comment by michaeltroger** [comment]
As of version 4, QR code and Aztec code are supported.
I'm not sure if regular barcodes is a use case coming that often, but I'm willing to change my opinion and keep this ticket open to see the demand

**Comment by hooger** [comment]
I have a couple of membership cards which contain a regular barcode. Those can be photoed and shown on the phone, and it would be better to have the code extracted. Just throwing it in as a possible use-case.

**Comment by michaeltroger** [comment]
Regular (1d) barcodes will be supported in the next release of the app
