### ISSUE TITLE
Support PDF417 barcodes

### ISSUE THREAD

**Issue by MarcMichalsky** [michaeltroger/greenpass-android#216]
Hi,

I'm actually opening this issue mainly to **thank you for your great work**! I use the app regularly and I love how simple the idea is and how versatile it is: train, movie or concert tickets or just any important document that you want to have at hand, everything can be found quickly and easily in one place. Ingenious!

So, now to my suggestion: A barcode type that is used quite frequently but is not yet supported is [PDF417](https://en.wikipedia.org/wiki/PDF417). I think it would be great if this type were also supported at some point.

Keep up the great work!

**Comment by michaeltroger** [comment]
Thx for the nice words! Glad you like the app.

PDF417 should be doable I think. I will give it a try.

**Comment by michaeltroger** [comment]
Will be part of the next version, together with DataMatrix support
