### ISSUE TITLE
Support data matrix and EAN Barcodes

### ISSUE THREAD

**Issue by D3SOX** [michaeltroger/greenpass-android#229]
I have tickets that use data matrix and EAN Barcodes. Could they be supported?
Can't you use some library for this similar to Barcode Scanner apps like [the one I use](https://gitlab.com/Atharok/BarcodeScanner) do?

**Comment by michaeltroger** [comment]
Those formats will be supported in the next version.
And yes, this app is using the ZXing library for barcodes as well

**Comment by D3SOX** [comment]
Thank you very much for the useful app
