### ISSUE TITLE
[ENHANCEMENT] Support particular Aztec QR Code extraction

### ISSUE THREAD

**Issue by Chepycou** [michaeltroger/greenpass-android#266]
**Is your feature request related to a problem? Please describe.**
I noticed some of the Aztec-like-looking QR-Codes are not extracted. Some new train tickets in France are using what looks like a special type of Aztec Qr-Codes (eg [here](https://www.youtube.com/watch?v=JoeQv9abPCs))

**Describe the solution you'd like**
If it's a totally different standard that happens to look the same then it's a feature request, else it's a bug report.

**Describe alternatives you've considered**
Not using the extract QR code feature

**Comment by michaeltroger** [comment]
Thx for reporting.
Can you please verify that you use app version 4.2.0?
There was recently an improvement for Aztec recognition.

If you already using the latest version you can try to scan the code on the PC with https://zxing-cpp.github.io/zxing-cpp/demo_reader.html or on Android with https://play.google.com/store/apps/details?id=de.markusfisch.android.binaryeye&hl=en_US
Both apps use the same technology as this app does - ZXing - to detect barcodes.

You can also share a (hand) drawing on how the layout of the PDF looks like - in particular where the Aztec code is located within the PDF page and how big it is. The rest of the page like any text doesn't matter. Please make sure to not share any private data

That would help narrowing down the problem.

**Comment by Chepycou** [comment]
Damn,
I was sure I had answered on the same day, but turns out my message was probably never sent. With the new update installed, the QR code in some train tickets in France were recognized, thanks !
