### ISSUE TITLE
Crowdin: Add Russian language

### ISSUE THREAD

**Issue by nm17** [michaeltroger/greenpass-android#49]
I want to help you with translating the app to Russian, but I can't find the language listed in Crowdin, can you add it as a language in your app? I'm willing to help you with the translation.

Also I can translate your Google Play page, I'll try to soon.

**Comment by michaeltroger** [comment]
Thx a lot!
It will be included in the next app update.
Do you want to be mentioned in the release notes? If yes with what name?

Meanwhile I shortened the app description for the Google Play page see:
https://github.com/michaeltroger/greenpass-android/blob/main/fastlane/metadata/android/en-US/title.txt
https://github.com/michaeltroger/greenpass-android/blob/main/fastlane/metadata/android/en-US/short_description.txt
https://github.com/michaeltroger/greenpass-android/blob/main/fastlane/metadata/android/en-US/full_description.txt
For translating Play store to Russian you would create a pull request and a new `fastlane/metadata/android/ru` directory with those files (title.txt etc.) including the translation.
But if you're not familiar with pull requests you can also post the translation of title, short and full description here and I will do the rest.
