### ISSUE TITLE
Different QR-Code in the preview

### ISSUE THREAD

**Issue by DrNion** [michaeltroger/greenpass-android#50]
The informations of both QRCodes stay identical though. Just the pixels are different.

To be honest I don't know if this creates a problem for other QRCode scanner. Just wanted to mention it fyi.

**Comment by michaeltroger** [comment]
This is working as designed. I also mention this in the [app description](https://github.com/michaeltroger/greenpass-android/blob/37/fastlane/metadata/android/en-US/full_description.txt#L31-L32):
So for the functionality of a QR code reader the visual appearance doesn't matter and I would call it a nice to have for the human eye only.

If you wish a more technical explanation:
The same QR code text content can be rendered with different [error correction levels](https://en.wikipedia.org/wiki/QR_code#Error_correction).
The library I'm using for reading QR codes (ZXing) doesn't seem to be capable of telling me the error correction of the original barcode (happy for any suggestions how to achieve that). Therefore I'm always using [the same error correction](https://github.com/michaeltroger/greenpass-android/blob/37/app/src/main/java/com/michaeltroger/gruenerpass/model/PdfRenderer.kt#L136-L138), no matter how the original barcode was rendered.

If something is still unclear then feel free to reopen this

**Comment by DrNion** [comment]
Thanks for the explanation, there is no need to reopen it then :)
