### ISSUE TITLE
wrong QR code is zoomed 

### ISSUE THREAD

**Issue by ghost** [michaeltroger/greenpass-android#56]
Hi

In France, certificates have two QR codes. One is to import the certificate into the official app, the other is the one that has to presented to be verified. 

The app does not select the right one when zooming in. The one that should be used is the one in the top right quadrant (it's larger now than it is in the screenshot below)

![1429298-le-nouveau-passe-sanitaire-europeen](https://user-images.githubusercontent.com/25869334/145784045-cd0a0bec-09b8-457b-94ae-4a72f08a3ef7.png)

Have a good day

**Comment by michaeltroger** [comment]
Hi! Thx for sharing your use case. So far the app only searches for a single QR code automatically. 
I guess one way to make it work would be to allow the user to selec the area in which the desired code can be found

**Comment by michaeltroger** [comment]
Sorry for the late response.
Selecting the barcode within the document turned out to be too complex for this free time project.
It's for sure not the solution you wished for, but from version 2.3.0 on you can at least disable the QR code extraction in the settings
