### ISSUE TITLE
pdf documents not loading after reposition

### ISSUE THREAD

**Issue by Bonidi** [michaeltroger/greenpass-android#57]
After reposition of documents (right or left move), part of stored pdf docum
![Screenshot_20211228_162436_com michaeltroger gruenerpass](https://user-images.githubusercontent.com/96784582/147581541-44e19e7f-7c00-4536-a259-60616f8a7ee9.jpg)
![Screenshot_20211228_162436_com michaeltroger gruenerpass](https://user-images.githubusercontent.com/96784582/147581573-e28f714b-32fc-4232-8696-35c7fc3f90e4.jpg)
ents are not loaded. Green mark is moving and only the name of the document is visible. Also QR code is not loaded, but only pdf document under it is visible.
After few restart the documents are loaded. But the same problem starts from time to time without any action. Just after restart of the Appl.

**Comment by michaeltroger** [comment]
Sorry I don't have a solution for this currently.
The PDF renderer I use (from Google) has sometimes device specific issues and it's in general not really powerful in terms of handling multiple documents at once.

**Comment by michaeltroger** [comment]
I think I found a solution for this after all, it will be part of the next 3.1.0 release
