### ISSUE TITLE
QR Code is not extracted for the Canadian Vaccine Certificate if there are more than 2 vaccine shots listed on the certificate  

### ISSUE THREAD

**Issue by 32423d** [michaeltroger/greenpass-android#58]
The QR code on the Canadian Vaccine Certificate is not extracted if there are more than 2 vaccine shots listed on the document. The reason for why there can be more than 2 vaccine shots listed on the document is if someone was to get a booster vaccine shot. The QR code on the Canadian Vaccine Certificate is still extracted if there are 1 or 2 vaccine shots listed on the document.

**Comment by michaeltroger** [comment]
The app only supports one qr code per document, if no QR code is detected then most likely because it's too small see https://github.com/michaeltroger/greenpass-android/issues/54
If not the desired QR code is extracted, please check https://github.com/michaeltroger/greenpass-android/issues/56
