### ISSUE TITLE
[Feature request] print pdf

### ISSUE THREAD

**Issue by Ayman-SHaaban-ELsayed** [michaeltroger/greenpass-android#65]
need button to print file please.

**Comment by Ayman-SHaaban-ELsayed** [comment]
when you can give us this update?
Thanks 😊 🌷

**Comment by michaeltroger** [comment]
Hi, personally I don't have time but external contribution is welcome

**Comment by Ayman-SHaaban-ELsayed** [comment]
Hi,
Thanks for your response,
I have tried to add print for the file,but i failed,can you give me an date
for this edit, please 🌷⚘

**Comment by Ayman-SHaaban-ELsayed** [comment]
hi, why you closed my issues ,we are helping each other,
All what I need is to add print button ,what is your recommendation steps about this.

**Comment by Ayman-SHaaban-ELsayed** [comment]
please help up by adding this feature.

**Comment by michaeltroger** [comment]
Printing will be possible with the latest version through the share functionality
