### ISSUE TITLE
Full screen page zoom

### ISSUE THREAD

**Issue by ghost** [michaeltroger/greenpass-android#66]
The current implementation limits the page zoom to its display frame, which is quite inconvenient if you want to show an enlarged fragment in full screen. I suggest adding a full screen zoom mode when you tap on a page (maybe double tap or something similar).

<details>
  <summary>Click to expand</summary>
  <img src="https://user-images.githubusercontent.com/34649010/159533750-65274f88-754e-4236-a454-a249416e88e4.png"/>
</details>

**Comment by michaeltroger** [comment]
Currently not planned, since the barcode is almost full screen already.

But will keep this issue open to see the demand

**Comment by michaeltroger** [comment]
A full screen display is possible with the new alternative list layout
