### ISSUE TITLE
current Uri

### ISSUE THREAD

**Issue by Ayman-SHaaban-ELsayed** [michaeltroger/greenpass-android#67]
Where can I find the current Uri in case that there is many pdf files opened and I change between them?

**Comment by michaeltroger** [comment]
Hi. With Uri you mean the full path where the file is stored?
The app imports the PDF if you open it, so it stores a copy of your document. The app doesn't remember the original file location. You can see the original filename (unless you renamed) on top of the document though. The file is securely stored within the private space of the app. Other apps have no access

**Comment by Ayman-SHaaban-ELsayed** [comment]
Hi thanks for your response, i mean where i can find the current path of
the current opened file in the saved file in the private space of the app?

**Comment by Ayman-SHaaban-ELsayed** [comment]
All what I need is to add print button,what is your recommendation steps about this,
I am not professional in kotlin.

**Comment by michaeltroger** [comment]
Closed because question is answered and for print there is https://github.com/michaeltroger/greenpass-android/issues/65
